# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Michele Fornino
title: PhD Candidate
email: mfornino@mit.edu
website: https::/mfornino.github.io/

# Dark Mode (true/false/never)
darkmode: never

# Social links
twitter_username: michele_fornino
github_username:  mfornino
# dribbble_username: jekyll
facebook_username: michele.fornino
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: michelefornino
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0002-9256-7252

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Michele and I am a PhD Candidate at MIT. 

  I grew up in Saluzzo, Italy.

  I am most skilled in: <mark>Coding</mark> and <mark>Teaching Undergraduate Macro</mark>

# Projects Section
projects_title: Research

# Experience Section
experience_title: Work Experience

# Education Section
# educaton_title: Education

# Awards Section
# awards_title: Awards

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

# Dark mode
 # darkmode: false (options: true, false, never)