# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Michele Fornino
title: PhD Candidate in Economics
email: mfornino@mit.edu
website: https::/mfornino.github.io/

# Dark Mode (true/false/never)
darkmode: never

# Social links
twitter_username: michele_fornino
github_username:  mfornino
# dribbble_username: jekyll
facebook_username: michele.fornino
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: michelefornino
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0002-9256-7252

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am an Economics PhD Candidate at the <a href="http://economics.mit.edu/">Massachusetts Institute of Technology (MIT)</a>. 

  I grew up in <a href="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.bookingpiemonte.it%2Fwp-content%2Fuploads%2F2015%2F08%2Fsaluzzo_hq.jpg&f=1&nofb=1">Saluzzo, Italy</a>. My name is <a href="https://forvo.com/word/michele/">a bit weird</a>.

  - <i>Research interests</i>: <mark>Macroeconomics</mark>, <mark>Economics of Automation</mark>, <mark>Labor Economics</mark>.

  - <i>Things I love doing</i>: <mark>Learning</mark>, <mark>Teaching</mark>, <mark>Coding</mark>

  - <i>Skills</i>:


# Projects Section
projects_title: Research

# Experience Section
experience_title: Work Experience

# Education Section
# educaton_title: Education

# Awards Section
# awards_title: Awards

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  <b>Awards</b>:
   - <i>"Particolarmente Meritevole"</i>. Honor mention from Bank of Italy's Stringher scholarship (2017).
   - <i>Marco Fanno Scholarship</i> from Unicredit&Universities Foundation (2014).
   - <i>Bocconi Full Merit Award</i>. Full scholarship awarded on the basis of merit from Bocconi University (2012).

  <b>Languages</b>: Italian (Native), English (Proficient), French and Spanish (Reading Competence).

  <b>Hobbies</b>:
   - <i>"Particolarmente Meritevole"</i>. Honor mention from Bank of Italy's Stringher scholarship (2017).
   - <i>Marco Fanno Scholarship</i> from Unicredit&Universities Foundation (2014).
   - <i>Bocconi Full Merit Award</i>. Full scholarship awarded on the basis of merit from Bocconi University (2012).

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

# Dark mode
 # darkmode: false (options: true, false, never)